CREATE OR REPLACE TABLE CITYLENS_MERGED_DB.CRIME_PUBLIC.STATION_NEIGHBORHOOD_MAP AS
SELECT * FROM VALUES
    ('Park Street',        'Downtown'),
    ('Downtown Crossing',  'Downtown'),
    ('South Station',      'South Boston'),
    ('North Station',      'North End'),
    ('Back Bay',           'Back Bay'),
    ('Fenway',             'Fenway'),
    ('Kenmore',            'Fenway'),
    ('Harvard',            'Allston'),
    ('Central',            'Allston'),
    ('Roxbury Crossing',   'Roxbury'),
    ('Jackson Square',     'Roxbury'),
    ('Ruggles',            'Roxbury'),
    ('Forest Hills',       'Jamaica Plain'),
    ('Green Street',       'Jamaica Plain'),
    ('Stony Brook',        'Jamaica Plain'),
    ('Fields Corner',      'Dorchester'),
    ('Shawmut',            'Dorchester'),
    ('Ashmont',            'Dorchester'),
    ('Mattapan',           'Mattapan'),
    ('Orient Heights',     'East Boston'),
    ('Airport',            'East Boston'),
    ('Maverick',           'East Boston'),
    ('Wood Island',        'East Boston'),
    ('Suffolk Downs',      'East Boston'),
    ('Beachmont',          'East Boston'),
    ('Revere Beach',       'East Boston'),
    ('Alewife',            'Allston'),
    ('Porter',             'Allston'),
    ('Hynes Convention',   'Back Bay'),
    ('Prudential',         'Back Bay'),
    ('Copley',             'Back Bay'),
    ('Arlington',          'Back Bay'),
    ('Boylston',           'Downtown'),
    ('Government Center',  'Downtown'),
    ('State',              'Downtown'),
    ('Aquarium',           'Downtown'),
    ('Chinatown',          'Chinatown'),
    ('Tufts Medical',      'South End'),
    ('Back Bay',           'South End'),
    ('Dudley',             'Roxbury'),
    ('Brigham Circle',     'Mission Hill'),
    ('Longwood',           'Longwood'),
    ('Brookline Village',  'Fenway'),
    ('Northeastern',       'Mission Hill'),
    ('Symphony',           'Mission Hill'),
    ('Mass Ave',           'South End'),
    ('Washington',         'South End'),
    ('Charlestown',        'Charlestown'),
    ('Community College',  'Charlestown'),
    ('Sullivan Square',    'Charlestown'),
    ('Assembly',           'Charlestown')
AS t(STATION_NAME, NEIGHBORHOOD_NAME);