-- Create cleaned crime table
CREATE OR REPLACE TABLE CRIME_CLEAN AS
SELECT
    INCIDENT_NUMBER,
    OFFENSE_CODE,
    OFFENSE_CODE_GROUP,
    OFFENSE_DESCRIPTION,
    DISTRICT,
    REPORTING_AREA,
    OCCURRED_ON_DATE,
    EXTRACT(YEAR FROM OCCURRED_ON_DATE) AS YEAR,
    EXTRACT(MONTH FROM OCCURRED_ON_DATE) AS MONTH,
    DAY_OF_WEEK,
    SHOOTING,
    UCR_PART
FROM CRIME_RAW
WHERE OCCURRED_ON_DATE IS NOT NULL;

-- This is to make sure all data was in there
-- SELECT DISTINCT 
--     EXTRACT(YEAR FROM OCCURRED_ON_DATE) AS YEAR
-- FROM CRIME_CLEAN
-- ORDER BY YEAR;
