-- This table converts individual crime records into aggregated monthly indicators.

CREATE OR REPLACE TABLE CRIME_MONTHLY AS
SELECT
    DATE_TRUNC('month', OCCURRED_ON_DATE) AS MONTH_DATE,
    COUNT(*) AS TOTAL_CRIME
FROM CRIME_CLEAN
GROUP BY MONTH_DATE
ORDER BY MONTH_DATE;

SELECT *
FROM CRIME_MONTHLY
ORDER BY MONTH_DATE;