CREATE OR REPLACE TABLE POLICY_DOCUMENTS (
    POLICY_ID STRING,
    SOURCE_FILE STRING,
    PAGE_NUMBER INT,
    CHUNK_ID STRING,
    CHUNK_TEXT STRING,
    EMBEDDING VECTOR(FLOAT, 768),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

TRUNCATE TABLE POLICY_DOCUMENTS;

COPY INTO POLICY_DOCUMENTS
(
    POLICY_ID,
    SOURCE_FILE,
    PAGE_NUMBER,
    CHUNK_ID,
    CHUNK_TEXT
)
FROM @policy_stage
PATTERN = '.*_chunks\.csv'
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

UPDATE POLICY_DOCUMENTS
SET EMBEDDING = SNOWFLAKE.CORTEX.EMBED_TEXT_768(
    'snowflake-arctic-embed-m',
    CHUNK_TEXT
)
WHERE EMBEDDING IS NULL;

SELECT COUNT(*) FROM POLICY_DOCUMENTS;
SELECT COUNT(*) FROM POLICY_DOCUMENTS WHERE EMBEDDING IS NOT NULL;

SELECT POLICY_ID, COUNT(*)
FROM POLICY_DOCUMENTS
GROUP BY POLICY_ID;
