-- 第一步：加 embedding 字段
ALTER TABLE CITYLENS_MERGED_DB.HOUSING_SERVING.SRV_HOUSING_QA_CONTEXT
ADD COLUMN EMBEDDING VECTOR(FLOAT, 768);

-- 第二步：生成 embedding
UPDATE CITYLENS_MERGED_DB.HOUSING_SERVING.SRV_HOUSING_QA_CONTEXT
SET EMBEDDING = SNOWFLAKE.CORTEX.EMBED_TEXT_768(
    'snowflake-arctic-embed-m', SUMMARY_TEXT
);

-- 第一步：加字段
ALTER TABLE CITYLENS_MERGED_DB.CITYLENS_SERVING.SRV_QA_CONTEXT
ADD COLUMN EMBEDDING VECTOR(FLOAT, 768);

-- 第二步：生成 embedding
UPDATE CITYLENS_MERGED_DB.CITYLENS_SERVING.SRV_QA_CONTEXT
SET EMBEDDING = SNOWFLAKE.CORTEX.EMBED_TEXT_768(
    'snowflake-arctic-embed-m', SUMMARY_TEXT
);

SELECT 
    ENTITY_NAME,
    SUMMARY_TEXT,
    VECTOR_COSINE_SIMILARITY(
        EMBEDDING,
        SNOWFLAKE.CORTEX.EMBED_TEXT_768(
            'snowflake-arctic-embed-m', 
            'most expensive neighborhood in Boston'
        )
    ) AS SIMILARITY
FROM CITYLENS_MERGED_DB.HOUSING_SERVING.SRV_HOUSING_QA_CONTEXT
ORDER BY SIMILARITY DESC
LIMIT 5;